### ISSUE TITLE
ServiceMenu.java:6: Вывод меню для заказа

### ISSUE THREAD

**Issue by 0pdd** [miroque/fast-cook#1]
The puzzle `1-d5473f3b` from #1 has to be resolved: 

https://github.com/miroque/fast-cook/blob/17452c1855c07a3273bee0100cded539ad63aa2c/src/main/java/ru/miroque/fastcook/services/ServiceMenu.java#L6-L6

The puzzle was created by @miroque on 10-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#1](https://github.com/miroque/fast-cook/issues/1) is still not solved.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#unknown]() is still not solved.

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#7](https://github.com/miroque/fast-cook/issues/7), [#8](https://github.com/miroque/fast-cook/issues/8), [#unknown]() are still not solved.

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#7](https://github.com/miroque/fast-cook/issues/7), [#unknown]() are still not solved; solved: [#8](https://github.com/miroque/fast-cook/issues/8).

**Comment by 0pdd** [comment]
@0pdd all 3 puzzles are solved here: [#7](https://github.com/miroque/fast-cook/issues/7), [#8](https://github.com/miroque/fast-cook/issues/8), [#unknown]().

**Comment by miroque** [comment]
ага, само оно не закрылось. 
ну оно и в начале как-то не очень то и открывалось
значит пока закрою самостоятельно
